export const BASE_URL = 'https://naka-env.org/api';

export const QUICK_ENDPOINTS = [
  {
    icon: '🏭',
    name: 'All Stations',
    path: '/stations',
    method: 'GET',
    stationId: '',
    sub: '',
    showCards: true,
  },
  {
    icon: '📍',
    name: 'Station Current',
    path: '/stations/{id}/current',
    method: 'GET',
    stationId: 'ST001',
    sub: 'current',
    showCards: false,
  },
  {
    icon: '📈',
    name: 'History 24h',
    path: '/stations/{id}/history',
    method: 'GET',
    stationId: 'ST001',
    sub: 'history?start={start_24h}&end={end_now}',
    showCards: false,
  },
  {
    icon: '📅',
    name: 'History 7 Days',
    path: '/stations/{id}/history',
    method: 'GET',
    stationId: 'ST001',
    sub: 'history?start={start_168h}&end={end_now}',
    showCards: false,
  },
  {
    icon: '🗓️',
    name: 'Monthly',
    path: '/stations/{id}/monthly',
    method: 'GET',
    stationId: 'ST001',
    sub: 'monthly?{current_month}',
    showCards: false,
  },
  {
    icon: '🔑',
    name: 'My API Key',
    path: '/keys/me',
    method: 'GET',
    stationId: '',
    sub: '',
    fullUrl: 'https://naka-env.org/api/keys/me',
    showCards: false,
  },
];
